name: Azure Static Web Apps CI/CD

on:
  workflow_run:
    workflows:
      - ReactJS Build
    branches:
      - main
    types:
      - completed

jobs:
  deploy_react_job:
    runs-on: ubuntu-latest
    name: Deploy job
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: react-build.yml
          workflow_conclusion: success
          name: build
          if_no_artifact_found: fail
          
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          api_location: 'api'
          output_location: ''
          skip_app_build: true