name: Azure Static Web Apps CI/CD

on:
  workflow_run:
    workflows:
      - "react-build"
    branches:
      - main
    types:
      - completed

jobs:
  deploy_react_job:
    runs-on: ubuntu-latest
    name: Deploy job
    steps:
      - uses: actions/checkout@v3
      
      # - name: Deploy
      #   id: deploy
      #   uses: Azure/static-web-apps-deploy@1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     action: 'upload'
      #     app_location: 'src/dist'
      #     api_location: 'api'
      #     output_location: ''
      #     skip_app_build: true