name: Create terraform plan

on:
  - pull_request

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for an example terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      AWS_DEFAULT_REGION: ap-southeast-1
    steps:
      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: gh-role-session
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          variables: |
            system_name = "portfolio"
            environment = "prd"
            location = "sa"
          backend_config_file: config/backend-prod.conf
          path: terraform